export const droneUsed = [
    'ACSL Soten',
    'AeroVironment Quantix',
    'AgEagle eBee',
    'Albris',
    'Autel',
    'Autel EVO Lite',
    'Autel EVO Nano',
    'Autel EVOII Dual 640T V1',
    'Autel EVOII Dual 640T V2',
    'Autel EVOII Dual Enterprise',
    'Autel EVOII Dual V1',
    'Autel EVOII Dual V2',
    'Autel EVOII Pro',
    'Autel EVOII V1',
    'Autel EVOII V2',
    'Autel EVOII V3',
    'Brinc Ball',
    'Brinc Lemur 2',
    'BROUAV D30L-8',
    'BROUAV D52L-8',
    'BROUAV D72L-8',
    'Delair UX11',
    'DJI Agras t10',
    'DJI Agras t16',
    'DJI Agras t20',
    'DJI Agras t30',
    'DJI Agras t40',
    'DJI Agras t50',
    'DJI Air',
    'DJI Air 2',
    'DJI Air 2S',
    'DJI Air 3',
    'DJI Avata',
    'DJI F330',
    'DJI F450',
    'DJI F550',
    'DJI FPV',
    'DJI Inspire 1',
    'DJI Inspire 1 Pro',
    'DJI Inspire 2',
    'DJI Inspire 3',
    'DJI M30',
    "DJI Matrice M100",
    "DJI Matrice M200",
    "DJI Matrice M200 V2",
    "DJI Matrice M210",
    "DJI Matrice M210 RTK",
    "DJI Matrice M210 RTK V2",
    "DJI Matrice M210 V2",
    "DJI Matrice M210RTK",
    "DJI Matrice M300",
    "DJI Matrice M300 RTK",
    "DJI Matrice M350",
    "DJI Matrice M350 RTK",
    "DJI Matrice M600",
    "DJI Matrice M600 Pro",
    "DJI Matrice M600P",
    "DJI Mavic 2 Enterprise",
    "DJI Mavic 2 Enterprise Advanced",
    "DJI Mavic 2 Enterprise Dual",
    "DJI Mavic 2 Enterprise Zoom",
    "DJI Mavic 2 Pro",
    "DJI Mavic 2 Zoom",
    "DJI Mavic 3",
    "DJI Mavic 3 CINE",
    "DJI Mavic 3 Classic",
    "DJI Mavic 3 Enterprise (on M3E remote)",
    "DJI Mavic 3 Enterprise Thermal (on M3E remote)",
    "DJI Mavic 3 Multispectral",
    "DJI Mavic 3 Multispectral (on M3M remote)",
    "DJI Mavic 3 Pro",
    "DJI Mavic 3T",
    "DJI Mavic Air",
    "DJI Mavic Air 2",
    "DJI Mavic Mini",
    "DJI Mavic Pro",
    "DJI Mavic Pro Platinum",
    "DJI Mini 2",
    "DJI Mini 2 SE",
    "DJI Mini 3",
    "DJI Mini 3 Pro",
    "DJI Mini 4 Pro",
    "DJI Mini SE",
    "DJI Phantom 3",
    "DJI M30T",
    "DJI Matrice M100",
    "DJI Matrice M200",
    "DJI Matrice M200 V2",
    "DJI Matrice M210",
    "DJI Matrice M210 RTK",
    "DJI Matrice M210 RTK V2",
    "DJI Matrice M210 V2",
    "DJI Matrice M210RTK",
    "DJI Matrice M300",
    "DJI Matrice M300 RTK",
    "DJI Matrice M350",
    "DJI Matrice M350 RTK",
    "DJI Matrice M600",
    "DJI Matrice M600 Pro",
    "DJI Matrice M600P",
    "DJI Mavic 2 Enterprise",
    "DJI Mavic 2 Enterprise Advanced",
    "DJI Mavic 2 Enterprise Dual",
    "DJI Mavic 2 Enterprise Zoom",
    "DJI Mavic 2 Pro",
    "DJI Mavic 2 Zoom",
    "DJI Mavic 3",
    "DJI Mavic 3 CINE",
    "DJI Mavic 3 Classic",
    "DJI Mavic 3 Enterprise (on M3E remote)",
    "DJI Mavic 3 Enterprise Thermal (on M3E remote)",
    "DJI Mavic 3 Multispectral",
    "DJI Mavic 3 Multispectral (on M3M remote)",
    "DJI Mavic 3 Pro",
    "DJI Mavic 3T",
    "DJI Mavic Air",
    "DJI Mavic Air 2",
    "DJI Mavic Mini",
    "DJI Mavic Pro",
    "DJI Mavic Pro Platinum",
    "DJI Mini 2",
    "DJI Mini 2 SE",
    "DJI Mini 3",
    "DJI Mini 3 Pro",
    "DJI Mini 4 Pro",
    "DJI Mini SE",
    "DJI Phantom 3",
    "DJI Phantom 3 Advanced",
    "DJI Phantom 3 Professional",
    "DJI Phantom 3 Standard",
    "DJI Phantom 4",
    "DJI Phantom 4 Advanced",
    "DJI Phantom 4 Pro",
    "DJI Phantom 4 Pro Obsidian",
    "DJI Phantom 4 Pro V2",
    "DJI Phantom 4 Pro V2.0",
    "DJI Phantom 4 RTK",
    "DJI S1000",
    "DJI S800",
    "DJI S800 EVO",
    "DJI S900",
    "Flyability Elios",
    "Flyability Elios 2",
    "Flyability Elios 3",
    "Flyability Elios 3 RAD Payload",
    "Flyability Elios 3 Surveying Payload",
    "Foxtech 160AG",
    "MAPIR",
    "Parrot Ai",
    "Parrot Anafi",
    "Parrot Anafi Thermal",
    "Parrot Anafi USA",
    "Quantum Trinity F90+",
    "Sentera",
    "Skydio S2+",
    "Skydio X10",
    "Skydio X10D",
    "Skydio X2",
    "Splashdrone 3+",
    "Splashdrone 4",
    "SwellPro 1",
    "SwellPro 2",
    "SwellPro 3",
    "SwellPro 4",
    "Wingtra",
    "XAG M2000",
    "XAG M500",
    "XAG P100",
    "XAG P100 Pro",
    "XAG P30 2018 rtk",
    "XAG P30 2020",
    "XAG R150",
    "XAG V40",
    "XAG XMission",
    "Yuneec",
    "Yuneec H",
    "Yuneec H+",
    "Yuneec H3",
    "Yuneec H520",
    "Other"
]

export const cameraSpecification = [
    "Autel EVOII Base",
    "Autel EVOII Pro",
    "DJI X3",
    "DJI X5",
    "DJI X4S",
    "DJI X5S",
    "DJI X7",
    "DJI XT2",
    "DJI P1",
    "DJI L1",
    "DJI L2",
    "H20",
    "H20T",
    "H20N",
    "Rockrobotic R2A",
    "Rockrobotic R360",
    "Sony a7R, a7R II",
    "Sony A6000",
    "Sony Multispectral Camera (MSZ-2100G)",
    "X5 RAW",
    "YellowScan",
    "Velodyne",
    "Other"
]

export const licenceList = [
    { value: 'No Licence yet', displayName: 'No Licence yet' },
    // { value: 'ARN', displayName: 'ARN (Aviation Reference Number) need to be validated to continue.' },
    { value: 'RPA (Remotely Piloted Aircraft)', displayName: 'RPA (Remotely Piloted Aircraft)' },
    { value: 'RePL (Remote Pilot Licence)', displayName: 'RePL (Remote Pilot Licence)' },
    { value: 'ReOC', displayName: 'ReOC' },

    // { value: 'CASA ACCOUNT', displayName: 'CASA ACCOUNT:' },
    // { value: 'RPA Operator accreditation from CASA', displayName: 'I have registered my drone and got and RPA operator accreditation from CASA' },
    // { value: 'RPA operator accreditation from CASA at a later date', displayName: 'I will register my drone and get and RPA operator accreditation from CASA at a later date' }
];